
export const SEED_EMPLOYEES = [
  { name: "Admire Musumhi", pin: "4219", department: "Knockout - Scouring Powder Department" },
  { name: "Agness Kadye", pin: "1156", department: "Matina - Brook Waters Department" },
  { name: "Alice Baboi", pin: "6000", department: "Matina - Rotary Line Department" },
  { name: "Alice Chigova", pin: "7731", department: "Knockout - Canteen Department" },
  { name: "Anesu Mutsamba", pin: "5578", department: "Knockout - Production Part-time" },
  { name: "Ashley Chapeyama", pin: "5417", department: "Matina - Admin Department" },
  { name: "Ashley Nyadhi", pin: "6815", department: "Matina - Production - Mixers" },
  { name: "Augustine Sambo", pin: "4243", department: "Knockout - Sales Team" },
  { name: "Auxilia Sakile Sibanda", pin: "4481", department: "Knockout - Sales Team" },
  { name: "Benjamin Chiviru", pin: "1562", department: "Matina - Drivers and Assistance Department" },
  { name: "Blessing Murira", pin: "2097", department: "Knockout - Sales Team" },
  { name: "Brian Marwa", pin: "6897", department: "Knockout - Petroleum Jelly Department" },
  { name: "Brilliant Munhuwe", pin: "4980", department: "Knockout - Sales Team" },
  { name: "Caleb Magadzo", pin: "8398", department: "Knockout - Admin Department" },
  { name: "Chido Chadzika", pin: "6323", department: "Knockout - Shop Attendants Department" },
  { name: "Chikomborero Majaheni", pin: "6888", department: "Knockout - Drivers Department" },
  { name: "Chipo Madzivanyika", pin: "9272", department: "Matina - Production - Mixers" },
  { name: "Clarence Mupfupi", pin: "2961", department: "Knockout - Drivers Department" },
  { name: "Constance Karinga", pin: "2718", department: "Matina - Stores Department" },
  { name: "Constance Nguwaya", pin: "5551", department: "Knockout - Sales Team" },
  { name: "Costa Mandizvidza", pin: "9519", department: "Knockout - Drivers Department" },
  { name: "Cynthia A Moyo Madanire", pin: "4454", department: "Knockout - Sales Team" },
  { name: "DUDZAI  APTON", pin: "1896", department: "Matina - Manual Labeling Department" },
  { name: "Daphine Gweshe", pin: "3547", department: "Matina - Manual Packing Department" },
  { name: "Dawn Muringami", pin: "3715", department: "Knockout - Sales Team" },
  { name: "Desire Chinoda", pin: "6139", department: "Matina - Rotary Line Department" },
  { name: "Edmore Meza", pin: "3778", department: "Knockout - General hand / Maintenance" },
  { name: "Elizabeth Fombe", pin: "6851", department: "Knockout - Labeling & Date Coding" },
  { name: "Elizabeth Mundanga", pin: "7480", department: "Knockout - Production - Dishwasher Filling" },
  { name: "Emily Moyo", pin: "4411", department: "Knockout - Sales Team" },
  { name: "Emmanuel Chideme", pin: "6658", department: "Matina - Concentrates Mixing Department" },
  { name: "Enock Motsi", pin: "4677", department: "Knockout - Vehicle Maintenance" },
  { name: "Esnath Muranda", pin: "2743", department: "Matina - Concentrates Mixing Department" },
  { name: "Esnath Muranda", pin: "5896", department: "Knockout - Production Part-time" },
  { name: "Evans Mwasembwa", pin: "4767", department: "Knockout - Production - Mixing" },
  { name: "Evelyne Jimu", pin: "9166", department: "Matina - Concentrates Mixing Department" },
  { name: "FAITH RUTENDO NTHALA", pin: "2026", department: "Knockout - Shop Attendants Department" },
  { name: "Fadzai Gwature", pin: "1680", department: "Knockout - Canteen Department" },
  { name: "Faith Franciko", pin: "1455", department: "Knockout - Sales Promoters Department" },
  { name: "Faith Natali", pin: "6728", department: "Knockout - Shop Attendants Department" },
  { name: "Faith Shiridzinonwa", pin: "6459", department: "Knockout - Shop Reliefer Department" },
  { name: "Faith Svinurai", pin: "3854", department: "Knockout - Sales Team" },
  { name: "Farai Karinga", pin: "2711", department: "Knockout - Production - Mixing" },
  { name: "Farai Katsande", pin: "8545", department: "Knockout - Admin Department" },
  { name: "Fidelis Maronga", pin: "1677", department: "MATINA - DISPATCH" },
  { name: "Foget Mavhunduke", pin: "2061", department: "Knockout - Drivers Department" },
  { name: "Forget Mavhunduke", pin: "4207", department: "Matina - Drivers and Assistance Department" },
  { name: "Francisca Denga", pin: "1510", department: "Knockout - Sales Team" },
  { name: "Frank Sithole", pin: "88888", department: "Matina - Drivers and Assistance Department" },
  { name: "Gabriel Gwariwa", pin: "9221", department: "Matina - Admin Department" },
  { name: "Gamuchirai Mukumba", pin: "8143", department: "Knockout - Sales Promoters Department" },
  { name: "Garikayi Tom", pin: "5299", department: "Knockout - Toilet Cleaners - Filling" },
  { name: "Given Mombo", pin: "5080", department: "Matina - Labeling Machine Department" },
  { name: "Happiness Makovore", pin: "8637", department: "Knockout - Sales Team" },
  { name: "Harrison Hiya", pin: "5100", department: "Knockout - Drivers Department" },
  { name: "Innocent Mvula", pin: "3325", department: "Matina - Sales Team Department" },
  { name: "Isaac Noah Chidembo", pin: "1560", department: "Knockout - Drivers Department" },
  { name: "Jethro Garanowako", pin: "5837", department: "Matina - Drivers and Assistance Department" },
  { name: "Joel Mandindo", pin: "9319", department: "Knockout - Vehicle Maintenance" },
  { name: "Joseph Mawoneke", pin: "1064", department: "Knockout - Drivers Department" },
  { name: "Judith Chikosha", pin: "8330", department: "Knockout - Shop Attendants Department" },
  { name: "Judith Manjeya", pin: "9163", department: "Knockout - Shop Attendants Department" },
  { name: "Justice Manhambara", pin: "6105", department: "Knockout - Drivers Department" },
  { name: "Kindness Boora", pin: "4221", department: "Matina - Rotary Line Department" },
  { name: "Kumbirai Too", pin: "2457", department: "Knockout - Production - Shrink Tunnel" },
  { name: "Kundiso Chiwira", pin: "9389", department: "Knockout - Toilet Cleaners - Filling" },
  { name: "LINOS MUNDORINGISA", pin: "1989", department: "Knockout - Drivers Department" },
  { name: "Lameck Chideme", pin: "9347", department: "Matina - Rotary Line Department" },
  { name: "Learnmore Mundoringisa", pin: "2668", department: "Knockout - Sales Team" },
  { name: "Leticia Tagwira", pin: "4735", department: "Knockout - Shop Attendants Department" },
  { name: "Listen Tarwireyi", pin: "2670", department: "Matina - Brook Waters Department" },
  { name: "Lloyd Chideme", pin: "3489", department: "Matina - Drivers and Assistance Department" },
  { name: "Lovemore Mashango", pin: "9620", department: "Knockout - Drivers Department" },
  { name: "Luckmore Kanyerere", pin: "3513", department: "Matina - Drivers and Assistance Department" },
  { name: "Makwavarara Rufaro", pin: "4199", department: "Knockout - Shop Attendants Department" },
  { name: "Manfred Kudemi", pin: "280308", department: "Knockout - Scouring Powder Department" },
  { name: "Margret Tobaiwa", pin: "4564", department: "Knockout - Labeling & Date Coding" },
  { name: "Marufu Bellington", pin: "6455", department: "Matina - Drivers and Assistance Department" },
  { name: "Masimba Mamutse", pin: "4543", department: "Matina - Laboratory Department" },
  { name: "Melody Tachiona", pin: "8194", department: "Knockout - Production - Date Coding" },
  { name: "Memory Zhakata", pin: "9950", department: "Knockout - Shop Attendants Department" },
  { name: "Mercy Nyamawara", pin: "8989", department: "Knockout - Sales Promoters Department" },
  { name: "Michael Gengezha", pin: "2796", department: "Knockout - Production Maintenance Department" },
  { name: "Michael Musengi", pin: "3108", department: "Knockout - Production - Date Coding" },
  { name: "Millicent V Makamba", pin: "2691", department: "Knockout - Sales Team" },
  { name: "Mufaro Marwa", pin: "2866", department: "Knockout - Stores & Dispatch" },
  { name: "Munashe Mugombe", pin: "1647", department: "Knockout - Production - Dishwasher Filling" },
  { name: "Munashe Nyamasvisva", pin: "7217", department: "Knockout - Drivers Department" },
  { name: "Munyaradzi Shiridzinonwa", pin: "8330", department: "Matina - Drivers and Assistance Department" },
  { name: "Mupfumbati Petronella", pin: "6096", department: "Knockout - Shop Attendants Department" },
  { name: "MwariAnesu Marwa", pin: "8788", department: "Knockout - Admin Department" },
  { name: "NIGEL Mativenga", pin: "8615", department: "Knockout - Vehicle Maintenance" },
  { name: "Naison Ronald Ranganai", pin: "6538", department: "Knockout - Drivers Department" },
  { name: "Natasha Majaheni", pin: "7385", department: "Knockout - Sales Promoters Department" },
  { name: "Natasha Nyamanhindi", pin: "4675", department: "Knockout - Shop Attendants Department" },
  { name: "Netsai Mhonda", pin: "8621", department: "Matina - Manual Labeling Department" },
  { name: "Ngedzo Ruvinga", pin: "6673", department: "Knockout - Toilet Cleaners - Labelling" },
  { name: "Obvious Gilimoni", pin: "6596", department: "Knockout - Drivers Department" },
  { name: "Olipah Mvula", pin: "5297", department: "Knockout - Production - Dishwasher Filling" },
  { name: "Owen Ruswa", pin: "7022", department: "Matina - Sales Team Department" },
  { name: "Panashe Dirwayi", pin: "4454", department: "Knockout - Drivers Department" },
  { name: "Pardon Ndongwe", pin: "2633", department: "Knockout - Drivers Department" },
  { name: "Passmore Benhura", pin: "2712", department: "Knockout - General hand / Maintenance" },
  { name: "Peter Lingomba", pin: "6348", department: "Knockout - Quality Control" },
  { name: "Pilan Matanga", pin: "7550", department: "Knockout - Production - Dishwasher Filling" },
  { name: "Prince Mwale", pin: "5851", department: "Knockout - Drivers Department" },
  { name: "Privilege Mundoringisa", pin: "7273", department: "Knockout - Admin Department" },
  { name: "Prosper Makonese", pin: "3034", department: "Knockout - Drivers Department" },
  { name: "Ranganai Mlambo", pin: "2391", department: "Knockout - Admin Department" },
  { name: "Raymond Takaedza Pumhu", pin: "8313", department: "Knockout - Drivers Department" },
  { name: "Remember Maronga", pin: "3479", department: "Matina - Rotary Line Department" },
  { name: "Roland Maguma", pin: "1974", department: "Matina - Drivers and Assistance Department" },
  { name: "Ruddy Muchada", pin: "5613", department: "Knockout - Production - Mixing" },
  { name: "Rudo Priscilla Masawi", pin: "8510", department: "Knockout - Shop Attendants Department" },
  { name: "Rumbidzai Chemwandoita", pin: "8523", department: "Knockout - Shop Attendants Department" },
  { name: "Rumbidzai Nhenderere", pin: "3402", department: "Matina - Manual Labeling Department" },
  { name: "Russel Shereni", pin: "3431", department: "Matina - Drivers and Assistance Department" },
  { name: "Rutendo Ruvinga", pin: "2984", department: "Knockout - Labeling & Date Coding" },
  { name: "Ruvimbo Chitenga", pin: "2592", department: "Knockout - Sales Team" },
  { name: "SIBONGILE CHITSAMBA ", pin: "2001", department: "Knockout - Quality Control" },
  { name: "Sandra Murombwi", pin: "6122", department: "Knockout - Sales Team" },
  { name: "Shantel Mazarura", pin: "2646", department: "Matina - Brook Waters Department" },
  { name: "Shelton Moto", pin: "9067", department: "Knockout - Scouring Powder Department" },
  { name: "Silence Muripo", pin: "8401", department: "Knockout - Sales Team" },
  { name: "Silvester Makore", pin: "8799", department: "Knockout - Drivers Department" },
  { name: "Simbarashe Mulauzi", pin: "8497", department: "Knockout - Vehicle Maintenance" },
  { name: "Sonny Makumpha", pin: "7940", department: "Matina - Drivers and Assistance Department" },
  { name: "Stacy Siziba", pin: "4524", department: "Knockout - Sales Team" },
  { name: "Tadiwanashe Marwa", pin: "1009", department: "Knockout - Drivers Department" },
  { name: "Takunda M Gweshe Admin", pin: "1313", department: "Knockout - Admin Department" },
  { name: "Tanaka Mahachi", pin: "4356", department: "Knockout - Production - Shrink Tunnel" },
  { name: "Tanaka Tsongorera", pin: "6203", department: "Knockout - Shop Attendants Department" },
  { name: "Tanatswa Machekera", pin: "1503", department: "Matina - Sales Team Department" },
  { name: "Tatenda Admire Nhidza", pin: "4824", department: "Knockout - Drivers Department" },
  { name: "Tatenda Mararike", pin: "1063", department: "Knockout - Production - Mixing" },
  { name: "Tatenda Mudombi", pin: "1920", department: "Knockout - Loading Department" },
  { name: "Tatenda Ruvinga", pin: "1317", department: "Knockout - Loading Department" },
  { name: "Tatenda Ruvinga--", pin: "6014", department: "Matina - Brook Waters Department" },
  { name: "Tatenda Stancia Nyamasvisva", pin: "9092", department: "Matina - Batching Department" },
  { name: "Taurayi Lantern", pin: "7874", department: "Knockout - Loading Department" },
  { name: "Tenderoyashe Mararike", pin: "3816", department: "Knockout - Sales Promoters Department" },
  { name: "Theophias Jasi", pin: "1784", department: "Matina - Drivers and Assistance Department" },
  { name: "Theophias Jussy--", pin: "2351", department: "Knockout - Drivers Department" },
  { name: "Tinashe Tangai", pin: "7261", department: "Knockout - Production Maintenance Department" },
  { name: "Tinashe Tsingano", pin: "5211", department: "Knockout - Admin Department" },
  { name: "Tinotenda Mapfumo", pin: "8934", department: "Knockout - Petroleum Jelly Department" },
  { name: "Tinotenda Muriro", pin: "6166", department: "Knockout - Drivers Department" },
  { name: "Tracey more Mbuzva", pin: "7646", department: "Knockout - Shop Reliefer Department" },
  { name: "Tracy Tachiona", pin: "4060", department: "Knockout - Production Part-time" },
  { name: "Trish Mbewe", pin: "4777", department: "Knockout - Sales Promoters Department" },
  { name: "Trish Soyala", pin: "8108", department: "Knockout - Admin Department" },
  { name: "Trymore Makuwerere", pin: "8469", department: "Knockout - Production - Shrink Tunnel" },
  { name: "Valery Mushaninga", pin: "6861", department: "Knockout - Shop Attendants Department" },
  { name: "Victoria Dickson", pin: "1145", department: "Knockout - Shop Attendants Department" },
  { name: "Vincent Tuwadya", pin: "4665", department: "Knockout - Admin Department" },
  { name: "Walter Chadamoyo", pin: "1765", department: "Knockout - Vehicle Maintenance" },
  { name: "Winfilda Ziyambi", pin: "6915", department: "Knockout - Sales Team" },
  { name: "Yemurai Mabhiza", pin: "8744", department: "Matina - Manual Packing Department" },
  { name: "Zvikomborero Kudumba", pin: "6206", department: "Knockout - Drivers Department" }
];
